import { useState, useEffect } from 'react';
import { Navigation } from '../components/Navigation';
import { Footer } from '../components/Footer';
import { Calendar, Plus, Trash2, MapPin, Clock, DollarSign, Download, Sparkles, Loader2, ShieldCheck, Globe } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';

interface ItineraryItem {
  id: string;
  day: number;
  title: string;
  location: string;
  time: string;
  cost: string;
  notes: string;
}

export function MyItinerary() {
  const [loading, setLoading] = useState(true);
  const [items, setItems] = useState<ItineraryItem[]>([
    {
      id: '1',
      day: 1,
      title: 'Arrival in Kigali',
      location: 'Kigali International Airport',
      time: '14:00',
      cost: '$0',
      notes: 'Hotel transfer included'
    },
    {
      id: '2',
      day: 1,
      title: 'Kigali Genocide Memorial',
      location: 'Kigali',
      time: '16:00',
      cost: 'Free',
      notes: 'Respectful attire required'
    },
    {
      id: '3',
      day: 2,
      title: 'Gorilla Trekking',
      location: 'Volcanoes National Park',
      time: '07:00',
      cost: '$1,500',
      notes: 'Bring hiking boots and rain jacket'
    },
  ]);

  const [showAddForm, setShowAddForm] = useState(false);
  const [newItem, setNewItem] = useState({
    day: 1,
    title: '',
    location: '',
    time: '',
    cost: '',
    notes: ''
  });

  // Simulate loading state for "Advanced" feel
  useEffect(() => {
    const timer = setTimeout(() => setLoading(false), 1500);
    return () => clearTimeout(timer);
  }, []);

  const addItem = () => {
    if (newItem.title && newItem.location) {
      const item: ItineraryItem = {
        id: Date.now().toString(),
        ...newItem
      };
      setItems([...items, item]);
      setNewItem({ day: 1, title: '', location: '', time: '', cost: '', notes: '' });
      setShowAddForm(false);
    }
  };

  const deleteItem = (id: string) => {
    setItems(items.filter(item => item.id !== id));
  };

  const groupedItems = items.reduce((acc, item) => {
    if (!acc[item.day]) {
      acc[item.day] = [];
    }
    acc[item.day].push(item);
    return acc;
  }, {} as Record<number, ItineraryItem[]>);

  const totalCost = items.reduce((sum, item) => {
    const cost = item.cost.replace(/[^0-9]/g, '');
    return sum + (cost ? parseInt(cost) : 0);
  }, 0);

  const exportItinerary = () => {
    const header = `
SURA RWANDA - STRATEGIC TRAVEL GUIDE
====================================
Generated on: ${new Date().toLocaleDateString()}
Total Duration: ${Object.keys(groupedItems).length} Days
Total Projected Budget: $${totalCost.toLocaleString()}
------------------------------------

`;
    let content = "";
    Object.keys(groupedItems).sort((a, b) => parseInt(a) - parseInt(b)).forEach(day => {
      content += `DAY ${day} SCHEDULE\n`;
      content += `---------------\n`;
      groupedItems[parseInt(day)].forEach(item => {
        content += `[${item.time || 'N/A'}] ${item.title}\n`;
        content += `Location: ${item.location}\n`;
        content += `Cost: ${item.cost || 'N/A'}\n`;
        if (item.notes) content += `Notes: ${item.notes}\n`;
        content += `\n`;
      });
      content += `\n`;
    });

    const footer = `
------------------------------------
Safe travels in the Land of a Thousand Hills!
Generated by Sura Rwanda AI
`;

    const blob = new Blob([header + content + footer], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = 'Sura_Rwanda_Strategic_Guide.txt';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  if (loading) {
    return (
      <div className="min-h-screen bg-white flex flex-col">
        <Navigation />
        <div className="flex-1 flex flex-col items-center justify-center space-y-8">
          <motion.div
            initial={{ scale: 0.8, opacity: 0 }}
            animate={{ scale: 1, opacity: 1 }}
            className="relative"
          >
             <motion.div
              animate={{ rotate: 360 }}
              transition={{ duration: 3, repeat: Infinity, ease: "linear" }}
              className="w-24 h-24 border-b-4 border-primary rounded-full"
            />
            <div className="absolute inset-0 flex items-center justify-center">
               <Globe className="w-8 h-8 text-primary animate-pulse" />
            </div>
          </motion.div>
          <div className="text-center">
            <motion.p
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ duration: 0.5, repeat: Infinity, repeatType: "reverse" }}
              className="text-slate-900 font-black tracking-[0.3em] uppercase text-xs mb-2"
            >
              Retrieving Digital Journey
            </motion.p>
            <p className="text-slate-400 text-[10px] font-medium italic">Synchronizing with Kigali Central Nodes...</p>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-white">
      <Navigation />

      <div className="max-w-5xl mx-auto px-6 py-12">
        <motion.div 
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          className="mb-12"
        >
          <div className="flex flex-col md:flex-row md:items-center justify-between gap-8">
            <div className="flex items-center gap-5">
              <div className="w-16 h-16 bg-primary text-white rounded-2xl flex items-center justify-center shadow-lg shadow-green-600/20">
                <Calendar className="w-8 h-8" />
              </div>
              <div>
                <h1 className="text-4xl md:text-6xl font-black text-slate-900 tracking-tighter uppercase leading-none">The Itinerary</h1>
                <p className="text-slate-500 font-medium italic mt-2">Your bespoke expedition through the Land of a Thousand Hills.</p>
              </div>
            </div>
            <button
              onClick={() => setShowAddForm(!showAddForm)}
              className="btn-primary flex items-center justify-center gap-2 group px-6 py-3 rounded-xl"
            >
              <Plus className="w-5 h-5 group-hover:rotate-180 transition-transform duration-500" />
              <span className="text-xs font-black uppercase tracking-widest">New Entry</span>
            </button>
          </div>
        </motion.div>

        {/* Summary Stats */}
        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.2 }}
          className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-16"
        >
          {[
            { label: 'Total Duration', value: `${Object.keys(groupedItems).length} Days`, icon: Calendar, color: 'text-primary', bg: 'bg-primary/5' },
            { label: 'Strategic Stops', value: `${items.length} Nodes`, icon: MapPin, color: 'text-blue-600', bg: 'bg-blue-50' },
            { label: 'Projected Budget', value: `$${totalCost.toLocaleString()}`, icon: DollarSign, color: 'text-amber-600', bg: 'bg-amber-50' },
          ].map((stat, i) => (
            <div key={i} className="glass rounded-[2rem] p-6 border-border shadow-sm flex items-center gap-4 transition-all hover:bg-white hover:shadow-xl hover:-translate-y-1">
              <div className={`p-3 rounded-xl ${stat.bg} ${stat.color}`}>
                <stat.icon className="w-6 h-6" />
              </div>
              <div>
                <p className="text-[9px] font-black text-slate-400 uppercase tracking-widest mb-0.5">{stat.label}</p>
                <p className="text-2xl font-black text-slate-900 tracking-tighter">{stat.value}</p>
              </div>
            </div>
          ))}
        </motion.div>

        {/* Add Form with Animation */}
        <AnimatePresence>
          {showAddForm && (
            <motion.div
              initial={{ opacity: 0, scale: 0.95, y: 20 }}
              animate={{ opacity: 1, scale: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.95, y: 20 }}
              className="mb-16"
            >
              <div className="glass rounded-[3rem] p-12 border-2 border-primary/20 shadow-2xl relative overflow-hidden bg-white">
                <div className="absolute top-0 right-0 p-12 opacity-5 pointer-events-none">
                  <Sparkles className="w-48 h-48 text-primary" />
                </div>
                <h3 className="text-3xl font-black text-slate-900 mb-10 flex items-center gap-4 uppercase tracking-tighter">
                  <Plus className="w-8 h-8 text-primary" />
                  Define Experience
                </h3>
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
                  <div className="space-y-3">
                    <label className="text-[10px] font-black uppercase tracking-widest text-slate-400">Target Day</label>
                    <input
                      type="number"
                      min="1"
                      value={newItem.day}
                      onChange={(e) => setNewItem({ ...newItem, day: parseInt(e.target.value) })}
                      className="w-full bg-slate-50 border-slate-100 rounded-2xl p-4 focus:ring-2 focus:ring-primary font-bold"
                    />
                  </div>
                  <div className="space-y-3">
                    <label className="text-[10px] font-black uppercase tracking-widest text-slate-400">Time Slot</label>
                    <input
                      type="time"
                      value={newItem.time}
                      onChange={(e) => setNewItem({ ...newItem, time: e.target.value })}
                      className="w-full bg-slate-50 border-slate-100 rounded-2xl p-4 focus:ring-2 focus:ring-primary font-bold"
                    />
                  </div>
                  <div className="space-y-3">
                    <label className="text-[10px] font-black uppercase tracking-widest text-slate-400">Activity Title *</label>
                    <input
                      type="text"
                      value={newItem.title}
                      onChange={(e) => setNewItem({ ...newItem, title: e.target.value })}
                      placeholder="e.g., Canopy Walk"
                      className="w-full bg-slate-50 border-slate-100 rounded-2xl p-4 focus:ring-2 focus:ring-primary font-bold"
                    />
                  </div>
                  <div className="space-y-3">
                    <label className="text-[10px] font-black uppercase tracking-widest text-slate-400">Official Location *</label>
                    <input
                      type="text"
                      value={newItem.location}
                      onChange={(e) => setNewItem({ ...newItem, location: e.target.value })}
                      placeholder="e.g., Nyungwe Forest"
                      className="w-full bg-slate-50 border-slate-100 rounded-2xl p-4 focus:ring-2 focus:ring-primary font-bold"
                    />
                  </div>
                  <div className="space-y-3">
                    <label className="text-[10px] font-black uppercase tracking-widest text-slate-400">Economic Value</label>
                    <input
                      type="text"
                      value={newItem.cost}
                      onChange={(e) => setNewItem({ ...newItem, cost: e.target.value })}
                      placeholder="e.g., $60"
                      className="w-full bg-slate-50 border-slate-100 rounded-2xl p-4 focus:ring-2 focus:ring-primary font-bold"
                    />
                  </div>
                  <div className="space-y-3">
                    <label className="text-[10px] font-black uppercase tracking-widest text-slate-400">Operational Notes</label>
                    <input
                      type="text"
                      value={newItem.notes}
                      onChange={(e) => setNewItem({ ...newItem, notes: e.target.value })}
                      placeholder="Special requirements"
                      className="w-full bg-slate-50 border-slate-100 rounded-2xl p-4 focus:ring-2 focus:ring-primary font-bold"
                    />
                  </div>
                </div>
                <div className="flex flex-wrap gap-4 mt-12">
                  <button onClick={addItem} className="btn-primary px-10">Confirm Synthesis</button>
                  <button onClick={() => setShowAddForm(false)} className="px-8 py-3 rounded-2xl font-black uppercase tracking-widest text-slate-400 hover:text-slate-600 transition-colors">Discard</button>
                </div>
              </div>
            </motion.div>
          )}
        </AnimatePresence>

        {/* Itinerary Timeline */}
        <div className="space-y-20 relative before:absolute before:left-[31px] before:top-0 before:bottom-0 before:w-1 before:bg-slate-50">
          {Object.keys(groupedItems).sort((a, b) => parseInt(a) - parseInt(b)).map((day, dayIdx) => (
            <motion.div 
              key={day}
              initial={{ opacity: 0, x: -20 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
              transition={{ delay: dayIdx * 0.1 }}
              className="relative z-10"
            >
              <div className="flex items-center gap-8 mb-10">
                <div className="w-16 h-16 bg-slate-900 text-white rounded-[1.5rem] flex items-center justify-center shadow-2xl ring-8 ring-white">
                  <span className="text-2xl font-black">0{day}</span>
                </div>
                <h2 className="text-3xl font-black text-slate-900 uppercase tracking-tighter">Day {day} Schedule</h2>
              </div>

              <div className="grid gap-8 pl-20">
                <AnimatePresence mode="popLayout">
                  {groupedItems[parseInt(day)].map((item, idx) => (
                    <motion.div
                      key={item.id}
                      layout
                      initial={{ opacity: 0, scale: 0.9, y: 20 }}
                      animate={{ opacity: 1, scale: 1, y: 0 }}
                      exit={{ opacity: 0, scale: 0.9, y: 20 }}
                      transition={{ delay: idx * 0.1, type: "spring", stiffness: 100 }}
                      className="card-lift glass rounded-[2rem] p-8 border-border shadow-sm group overflow-hidden relative bg-white hover:bg-slate-50/50"
                    >
                      <div className="absolute top-0 right-0 w-2 h-full bg-primary opacity-0 group-hover:opacity-100 transition-opacity"></div>
                      <div className="flex items-start justify-between gap-6">
                        <div className="flex-1">
                          <div className="flex flex-wrap items-center gap-4 mb-4">
                            {item.time && (
                              <span className="flex items-center gap-2 px-3 py-1 bg-primary/10 text-primary text-[9px] font-black rounded-full uppercase tracking-widest">
                                <Clock className="w-3 h-3" />
                                {item.time}
                              </span>
                            )}
                            <span className="flex items-center gap-2 text-slate-400 text-[9px] font-black uppercase tracking-widest">
                              <MapPin className="w-3 h-3 text-primary" />
                              {item.location}
                            </span>
                            {item.cost && (
                              <span className="flex items-center gap-2 text-slate-900 text-[9px] font-black uppercase tracking-widest">
                                <DollarSign className="w-3 h-3 text-primary" />
                                {item.cost}
                              </span>
                            )}
                          </div>
                          <h3 className="text-xl font-black text-slate-900 mb-3 group-hover:text-primary transition-colors tracking-tighter uppercase leading-none">{item.title}</h3>
                          {item.notes && (
                            <div className="flex gap-3 p-4 bg-slate-50 rounded-xl border border-slate-100 mt-6 relative">
                              <Sparkles className="w-4 h-4 text-primary shrink-0 animate-pulse" />
                              <p className="text-xs text-slate-600 font-medium italic leading-relaxed border-l-2 border-primary/20 pl-3">{item.notes}</p>
                            </div>
                          )}
                        </div>
                        <button
                          onClick={() => deleteItem(item.id)}
                          className="p-3 bg-red-50 text-red-500 rounded-xl opacity-0 group-hover:opacity-100 transition-all hover:bg-red-500 hover:text-white shadow-lg"
                        >
                          <Trash2 className="w-5 h-5" />
                        </button>
                      </div>
                    </motion.div>
                  ))}
                </AnimatePresence>
              </div>
            </motion.div>
          ))}
        </div>

        {items.length === 0 && (
          <motion.div 
            initial={{ opacity: 0, scale: 0.9 }}
            animate={{ opacity: 1, scale: 1 }}
            className="text-center py-32 glass rounded-[3rem] border-dashed border-4 border-slate-100 bg-slate-50/50"
          >
            <div className="w-24 h-24 bg-white rounded-full flex items-center justify-center mx-auto mb-8 shadow-xl">
              <Calendar className="w-12 h-12 text-slate-200" />
            </div>
            <h3 className="text-3xl font-black text-slate-900 mb-3 uppercase tracking-tighter">Tabula Rasa</h3>
            <p className="text-slate-500 mb-10 max-w-sm mx-auto font-medium italic">Your Rwanda journey remains unwritten. Synthesize your first experience.</p>
            <button
              onClick={() => setShowAddForm(true)}
              className="btn-primary px-12 py-5 rounded-2xl"
            >
              Initialize Expedition
            </button>
          </motion.div>
        )}

        {/* Action Footer */}
        {items.length > 0 && (
          <motion.div 
            initial={{ opacity: 0 }}
            whileInView={{ opacity: 1 }}
            className="mt-16 text-center space-y-6"
          >
            <button 
              onClick={exportItinerary}
              className="inline-flex items-center gap-3 px-8 py-4 bg-slate-900 text-white rounded-2xl font-black uppercase tracking-tighter hover:bg-slate-800 transition-all hover:shadow-2xl active:scale-95 group"
            >
              <Download className="w-6 h-6 group-hover:animate-bounce" />
              <span className="text-base">Export Strategic Guide</span>
            </button>
            <div className="flex items-center justify-center gap-3 text-slate-400">
               <ShieldCheck className="w-4 h-4 text-primary" />
               <span className="text-[9px] font-black uppercase tracking-[0.3em]">Encrypted Cloud Sync Active</span>
            </div>
          </motion.div>
        )}
      </div>
      <Footer />
    </div>
  );
}