export const dummyPlaces = [
  // Parks
  {
    id: 'volcanoes-national-park',
    name: 'Volcanoes National Park',
    category: 'Parks',
    duration: '1-2 days',
    price: '$$$',
    rating: 5,
    activities: ['Gorilla trekking', 'Golden monkey tracking', 'Volcano hiking', 'Nature walks'],
    description: 'A top wildlife destination in Rwanda known for gorilla trekking and volcanic scenery.',
    image: '/images/attractions/parks/volcanoes-park.jpg',
  },
  {
    id: 'akagera-national-park',
    name: 'Akagera National Park',
    category: 'Parks',
    duration: '1-2 days',
    price: '$$',
    rating: 4.6,
    activities: ['Game drives', 'Boat safaris', 'Bird watching', 'Big Five safari'],
    description: 'Rwanda’s savannah park with classic safari wildlife and lakeside landscapes.',
    image: '/images/attractions/parks/akagera-park.jpg',
  },
  {
    id: 'nyungwe-forest',
    name: 'Nyungwe Forest National Park',
    category: 'Parks',
    duration: '2-3 days',
    price: '$$',
    rating: 4.7,
    activities: ['Canopy walk', 'Chimpanzee trekking', 'Birding', 'Hiking trails'],
    description: 'One of the oldest rainforests in Africa, rich in biodiversity and home to chimpanzees.',
    image: '/images/attractions/parks/nyungwe-forest.jpg',
  },
  {
    id: 'gishwati-park',
    name: 'Gishwati-Mukura Park',
    category: 'Parks',
    duration: '1 day',
    price: '$',
    rating: 4.2,
    activities: ['Primate tracking', 'Bird watching', 'Nature hikes'],
    description: 'Rwanda’s newest national park, featuring restored montane forests.',
    image: '/images/attractions/parks/gishwati-park.jpg',
  },
  
  // Lakes
  {
    id: 'lake-kivu',
    name: 'Lake Kivu (Rubavu)',
    category: 'Lakes',
    duration: '2-3 days',
    price: '$$',
    rating: 4.8,
    activities: ['Kayaking', 'Boat rides', 'Beach relaxation', 'Sunset cruises'],
    description: 'One of Africa’s Great Lakes, popular for relaxation and lakeside tourism.',
    image: '/images/attractions/lakes/lake-kivu.jpg',
  },
  {
    id: 'lake-burera',
    name: 'Lake Burera & Ruhondo',
    category: 'Lakes',
    duration: '1 day',
    price: '$',
    rating: 4.5,
    activities: ['Canoeing', 'Island visits', 'Photography', 'Camping'],
    description: 'The "Twin Lakes" located at the base of the Virunga volcanoes.',
    image: '/images/attractions/lakes/lake-burera.jpg',
  },
  {
    id: 'lake-muhazi',
    name: 'Lake Muhazi',
    category: 'Lakes',
    duration: '1 day',
    price: '$$',
    rating: 4.3,
    activities: ['Boating', 'Fishing', 'Lakeside dining', 'Birding'],
    description: 'A serene getaway near Kigali, perfect for a day trip or weekend retreat.',
    image: '/images/attractions/lakes/lake-muhazi.jpg',
  },

  // Mountains
  {
    id: 'mount-bisoke',
    name: 'Mount Bisoke',
    category: 'Mountains',
    duration: '1 day',
    price: '$$',
    rating: 4.7,
    activities: ['Crater lake hike', 'Photography', 'Volcano climbing'],
    description: 'An active volcano in the Virunga Mountains with a beautiful crater lake at the summit.',
    image: '/images/attractions/mountains/mount-bisoke.jpg',
  },
  {
    id: 'mount-karisimbi',
    name: 'Mount Karisimbi',
    category: 'Mountains',
    duration: '2 days',
    price: '$$$',
    rating: 4.9,
    activities: ['High-altitude trekking', 'Camping', 'Snow-capped peak views'],
    description: 'The highest peak in Rwanda, offering a challenging but rewarding climb.',
    image: '/images/attractions/mountains/mount-karisimbi.jpg',
  },

  // Cities
  {
    id: 'kigali-city',
    name: 'Kigali City',
    category: 'Cities',
    duration: '2 days',
    price: '$$',
    rating: 4.9,
    activities: ['City tours', 'Markets', 'Museums', 'Cafe hopping'],
    description: 'Rwanda’s capital city, known for cleanliness, safety, and a growing food and arts scene.',
    image: '/images/attractions/cities/kigali.jpg',
  },
  {
    id: 'gisenyi-city',
    name: 'Rubavu (Gisenyi)',
    category: 'Cities',
    duration: '2 days',
    price: '$$',
    rating: 4.6,
    activities: ['Beach sports', 'Hot springs', 'Waterfront dining'],
    description: 'A vibrant resort town on the shores of Lake Kivu, near the DR Congo border.',
    image: '/images/attractions/cities/gisenyi.jpg',
  },
  {
    id: 'huye-city',
    name: 'Huye (Butare)',
    category: 'Cities',
    duration: '1-2 days',
    price: '$',
    rating: 4.4,
    activities: ['National Museum visit', 'University tours', 'Cultural learning'],
    description: 'The intellectual and cultural hub of Rwanda, home to the Ethnographic Museum.',
    image: '/images/attractions/cities/huye.jpg',
  },

  // Culture
  {
    id: 'king-palace',
    name: 'King\'s Palace Museum',
    category: 'Culture',
    duration: 'Half day',
    price: '$',
    rating: 4.7,
    activities: ['Royal history', 'Inyambo cattle', 'Traditional architecture'],
    description: 'A reconstruction of the traditional royal residence in Nyanza.',
    image: '/images/attractions/culture/king-palace.jpg',
  },
  {
    id: 'genocide-memorial',
    name: 'Kigali Genocide Memorial',
    category: 'Culture',
    duration: 'Half day',
    price: 'Free',
    rating: 5,
    activities: ['Historical education', 'Commemoration', 'Peace building'],
    description: 'A powerful place of remembrance for the victims of the 1994 Genocide.',
    image: '/images/attractions/culture/genocide-memorial.jpg',
  },
  {
    id: 'culture-village',
    name: 'Iby\'iwacu Cultural Village',
    category: 'Culture',
    duration: 'Half day',
    price: '$$',
    rating: 4.8,
    activities: ['Traditional dance', 'Local archery', 'Medicinal plant learning'],
    description: 'A community-run project showcasing traditional Rwandan rural life.',
    image: '/images/attractions/culture/culture-village.jpg',
  },
  {
    id: 'musanze-caves',
    name: 'Musanze Caves',
    category: 'Culture',
    duration: '2-3 hours',
    price: '$$',
    rating: 4.3,
    activities: ['Caving', 'Geology', 'Historical exploration'],
    description: 'Ancient lava tubes used as shelters during various historical periods.',
    image: '/images/attractions/culture/musanze-caves.jpg',
  },
];

export const dummyFoods = [
  { id: 'ugali', name: 'Ugali (Ubugali)', category: 'Main Dish', price: '$', mustTry: true, ingredients: ['Maize flour', 'Water'], image: '/images/food/ugali.jpg', description: 'Popular in Rwanda and East Africa, ugali is worth trying while you travel.' },
  { id: 'isombe', name: 'Isombe', category: 'Main Dish', price: '$', mustTry: true, ingredients: ['Cassava leaves', 'Peanut butter', 'Palm oil'], image: '/images/food/isombe.jpg', description: 'Popular in Rwanda and East Africa, isombe is worth trying while you travel.' },
  { id: 'brochette', name: 'Brochette', category: 'Street Food', price: '$$', mustTry: true, ingredients: ['Beef', 'Goat', 'Chicken', 'Spices'], image: '/images/food/brochettes.jpg', description: 'Popular in Rwanda and East Africa, brochette is worth trying while you travel.' },
  { id: 'isambaza', name: 'Sambaza', category: 'Street Food', price: '$', mustTry: true, ingredients: ['Lake fish', 'Oil', 'Salt'], image: '/images/food/sambaza.jpg', description: 'Popular in Rwanda and East Africa, sardine is worth trying while you travel.' },
];

export const dummyRestaurants = [
  { id: 'heaven-restaurant', name: 'Heaven Restaurant', location: 'Kigali', specialty: 'International & Local Fusion', price: '$$$', rating: 4.7 },
  { id: 'the-hut', name: 'The Hut', location: 'Kigali', specialty: 'Traditional Rwandan', price: '$$', rating: 4.4 },
];
